services:

  # -----------------------------------------------------------
  # ZOOKEEPER
  # -----------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # -----------------------------------------------------------
  # KAFKA BROKER
  # -----------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  # -------------------------
  # PRODUCER
  producer:
    build: .
    container_name: producer
    depends_on:
      kafka:
        condition: service_healthy
    command: python -u ingestion/producer.py
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1

  # -------------------------
  # SPARK STREAMING
  # -------------------------
  spark-processor:
    build: .
    container_name: spark-processor
    depends_on:
      - kafka
    command: python processing/spark_streaming.py
    volumes:
      - .:/app
      - spark_checkpoints:/tmp/checkpoints
    environment:
      PYTHONUNBUFFERED: 1
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: python
      PYTHONPATH: /app

  # -------------------------
  # POSTGRESQL
  # -------------------------
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  # -------------------------
  # REDIS
  # -------------------------
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # -------------------------
  # ML TRAINER
  # -------------------------
  trainer:
    build: .
    container_name: ml-trainer
    depends_on:
      - postgres
      - redis
    command: python training/train_model.py
    volumes:
      - .:/app

  # -------------------------
  # DASHBOARD
  # -------------------------
  dashboard:
    build: .
    container_name: dashboard
    depends_on:
      - redis
      - postgres
    command: python dashboard.py
    ports:
      - "8050:8050"
    volumes:
      - .:/app

  # -------------------------
  # GRAFANA
  # -------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: redis-datasource
    volumes:
      - grafana_data:/var/lib/grafana

# -------------------------
# VOLUMES
# -------------------------
volumes:
  kafka_data:
  postgres_data:
  spark_checkpoints:
  grafana_data:
